-- RBAC: SUPER_ADMIN, GOV, REVIEWER；委員舊值 COMMITTEE 遷移至 REVIEWER
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'GOV';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'REVIEWER';

UPDATE "User" SET role = 'REVIEWER'::"Role" WHERE role = 'COMMITTEE'::"Role";

UPDATE "User" SET role = 'SUPER_ADMIN'::"Role" WHERE LOWER(email) = LOWER('52828plus@gmail.com');
